#!/usr/bin/env bash
# ---------------------------------------------------------------------------
# Session Setup: fetch secrets from GitHub and download S3 database.
#
# Prerequisites (one-time):
#   gh auth login          # Authenticate the GitHub CLI
#
# Usage:
#   bash scripts/setup_session.sh              # Full setup
#   bash scripts/setup_session.sh --secrets    # Only fetch secrets to .env
#   bash scripts/setup_session.sh --db         # Only download DB from S3
#   bash scripts/setup_session.sh --skip-db    # Secrets only, skip S3 download
# ---------------------------------------------------------------------------
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
PROJECT_DIR="$(dirname "$SCRIPT_DIR")"
ENV_FILE="$PROJECT_DIR/.env"
DB_PATH="$PROJECT_DIR/horse_racing.db"
REPO="tomwilson41986/ashcroft"

FETCH_SECRETS=true
FETCH_DB=true

for arg in "$@"; do
    case "$arg" in
        --secrets)  FETCH_DB=false ;;
        --db)       FETCH_SECRETS=false ;;
        --skip-db)  FETCH_DB=false ;;
    esac
done

# ---------------------------------------------------------------------------
# Step 1: Verify gh CLI is authenticated
# ---------------------------------------------------------------------------
if ! gh auth status &>/dev/null; then
    echo "ERROR: gh CLI is not authenticated."
    echo "Run: gh auth login"
    exit 1
fi
echo "[OK] gh CLI authenticated"

# ---------------------------------------------------------------------------
# Step 2: Fetch secrets from GitHub repository
# ---------------------------------------------------------------------------
if [ "$FETCH_SECRETS" = true ]; then
    echo "Fetching secrets from GitHub repo ($REPO)..."

    # List of secrets to fetch — gh can't read secret values directly,
    # but we can use the GitHub API to check which secrets exist.
    # We'll set them via gh secret get (which requires a workaround).

    # gh doesn't support reading secret values (by design — they're write-only).
    # Instead, we use repository environment variables or gh variables.
    # For secrets that ARE available, we fetch via GitHub Actions API.

    # Strategy: Use gh to trigger a helper workflow that exports secrets,
    # OR store non-sensitive config as gh variables and secrets in .env.

    # Practical approach: store secrets as gh variables (non-secret config)
    # and prompt for actual secrets only once, caching in .env.

    # Fetch repository variables (non-secret config)
    echo "Fetching repository variables..."
    VARS=$(gh api "repos/$REPO/actions/variables" --jq '.variables[] | "\(.name)=\(.value)"' 2>/dev/null || echo "")

    # Start building .env
    echo "# Auto-generated by scripts/setup_session.sh" > "$ENV_FILE"
    echo "# $(date -Iseconds)" >> "$ENV_FILE"
    echo "" >> "$ENV_FILE"

    if [ -n "$VARS" ]; then
        echo "# Repository variables" >> "$ENV_FILE"
        echo "$VARS" >> "$ENV_FILE"
        echo "" >> "$ENV_FILE"
    fi

    # For actual secrets, check if they're already cached in .env.local
    LOCAL_ENV="$PROJECT_DIR/.env.local"
    if [ -f "$LOCAL_ENV" ]; then
        echo "Loading cached secrets from .env.local..."
        cat "$LOCAL_ENV" >> "$ENV_FILE"
    else
        # Fetch the secret names to know what we need
        echo "Checking which secrets are configured..."
        SECRET_NAMES=$(gh api "repos/$REPO/actions/secrets" --jq '.secrets[].name' 2>/dev/null || echo "")

        if [ -n "$SECRET_NAMES" ]; then
            echo "Repository has these secrets configured:"
            echo "$SECRET_NAMES" | sed 's/^/  - /'
            echo ""
            echo "GitHub secrets are write-only (can't be read via API)."
            echo "Enter values below to cache them in .env.local (gitignored)."
            echo "Press Enter to skip any secret you don't need locally."
            echo ""

            > "$LOCAL_ENV"

            for secret in $SECRET_NAMES; do
                # Check if already in env
                current_val="${!secret:-}"
                if [ -n "$current_val" ]; then
                    echo "$secret=$current_val" >> "$LOCAL_ENV"
                    echo "  $secret: [from environment]"
                else
                    read -rp "  $secret: " val
                    if [ -n "$val" ]; then
                        echo "$secret=$val" >> "$LOCAL_ENV"
                    fi
                fi
            done

            cat "$LOCAL_ENV" >> "$ENV_FILE"
            echo ""
            echo "Secrets cached in .env.local (gitignored)"
        fi
    fi

    # Ensure defaults for S3 config
    grep -q "S3_BUCKET" "$ENV_FILE" || echo "S3_BUCKET=horseracingresults" >> "$ENV_FILE"
    grep -q "S3_DB_KEY" "$ENV_FILE" || echo "S3_DB_KEY=horse_racing.db" >> "$ENV_FILE"
    grep -q "AWS_DEFAULT_REGION" "$ENV_FILE" || echo "AWS_DEFAULT_REGION=us-east-1" >> "$ENV_FILE"

    echo "[OK] .env written to $ENV_FILE"
fi

# ---------------------------------------------------------------------------
# Step 3: Download database from S3
# ---------------------------------------------------------------------------
if [ "$FETCH_DB" = true ]; then
    # Source the env file for AWS credentials
    set -a
    source "$ENV_FILE"
    set +a

    if [ -z "${AWS_ACCESS_KEY_ID:-}" ] || [ -z "${AWS_SECRET_ACCESS_KEY:-}" ]; then
        echo "WARNING: AWS credentials not found in .env"
        echo "Cannot download database from S3."
        echo "Add AWS_ACCESS_KEY_ID and AWS_SECRET_ACCESS_KEY to .env.local"
        exit 1
    fi

    echo "Downloading database from S3..."
    python "$PROJECT_DIR/scripts/fetch_data.py" \
        --db-only \
        --s3-bucket "${S3_BUCKET:-horseracingresults}" \
        --s3-key "${S3_DB_KEY:-horse_racing.db}" \
        --db-path "$DB_PATH"

    if [ -f "$DB_PATH" ]; then
        SIZE=$(du -h "$DB_PATH" | cut -f1)
        ROWS=$(python -c "import sqlite3; c=sqlite3.connect('$DB_PATH'); print(c.execute('SELECT COUNT(*) FROM race_results').fetchone()[0]); c.close()" 2>/dev/null || echo "?")
        echo "[OK] Database downloaded: $DB_PATH ($SIZE, $ROWS rows)"
    else
        echo "ERROR: Database download failed"
        exit 1
    fi
fi

echo ""
echo "Session setup complete!"
echo "  .env:      $ENV_FILE"
echo "  Database:  $DB_PATH"
echo ""
echo "Run predictions:  python predict_bfsp_today.py"
echo "Train model:      python train_bfsp.py"
